Main page
dskiba/airbnb-demo-frontend pull request #1
Opened 2018-01-06 00:26 UTC by dskiba

Доделал основную старницу,
завтра днем закончу адаптив, для планшета и мобайл

2018-01-06 20:39 UTC, dskiba commented
Закончил Main-Page с адаптивом.

2018-01-07 22:21 UTC, imevro requested changes

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Header/index.jsx
> +import shape from "./shape.png";
тупое название и почему иконка в пнг

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Header/index.jsx
> +import arrow from "../Footer/arrow.svg";
зачем ты из хедера ходишь в футер? это нелогично

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Footer/styled.js
> +  @media (max-width: 768px) {
без max-width, потому что mobile first и работа с min-width

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Header/Navigation.js
> +const LinkList = styled.li`
тупое название "список ссылок"

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Header/index.jsx
> +        <Col xs={2} md={1} lg={1}>
зачем тут сетка?

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Header/index.jsx
> +    <div className="container">
есть Grid в реакт-фбг

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Main/Experiences/index.js
> +              <br />
br только для текстов

2018-01-07 22:21 UTC, evgenyrodionov commented on src/Main/Explore/index.js
> +    height: 72px;
нельзя задавать ширину или высоту чему-либо кроме картинок

2018-01-07 22:21 UTC, evgenyrodionov commented on src/main/index.js
> +import React from "react";
название директории смени, почему `main`, а не `Main`?

2018-01-09 22:25 UTC, merged