Featuring/homes page
dskiba/airbnb-demo-frontend pull request #3
Opened 2018-01-12 02:49 UTC by dskiba

Сделал:
Изменил компоненты карточек страницы Main, для того чтобы добавить props;
Добавил UI категорию.
Закончил версту старницы Homes, без фильтров;
приобщил react-routing.
deploy: https://build-yxadxicley.now.sh/

пока ломаю голову со стейтами в  day-picker.

2018-01-12 17:03 UTC, evgenyrodionov commented
Чё это за закругление + картинка мыльная
![image](https://user-images.githubusercontent.com/775692/34886243-7ec9b08e-f7d3-11e7-9834-cb167785163d.png)

---

Всё сжалось-прижалось
![image](https://user-images.githubusercontent.com/775692/34886283-978e8572-f7d3-11e7-809c-9e5a0a390ecc.png)

---
Шрифты внизу не те
![image](https://user-images.githubusercontent.com/775692/34886294-a2d6bcf6-f7d3-11e7-8ca8-34d74a721fd9.png)

2018-01-12 17:07 UTC, imevro requested changes

2018-01-12 17:07 UTC, evgenyrodionov commented on .vscode/settings.json
> +  "typescript.tsdk": "node_modules/typescript/lib"
зачем это в репо? выкинь мусор и в гитигнор всю `.vscode`

2018-01-12 17:07 UTC, evgenyrodionov commented on src/Homes/Cards/Card.js
> +  font-family: "Circular_Air-Light";
Тебе удобно ваще так? Не проще ли `Circular Air Light`?

2018-01-12 17:07 UTC, evgenyrodionov commented on src/Homes/Cards/Card.js
> +const CardImg = Img.extend`
ты и так в карточке…

2018-01-12 17:07 UTC, evgenyrodionov commented on src/Homes/Cards/index.js
> +import img3 from "../../Main/Homes/3.png";
тебе не кажетя что в хоумс тебе нужно идти в лэндинг? не логичнее ли наоборот?

2018-01-13 08:50 UTC, dskiba commented
Деплой: https://build-ldvoriuarm.now.sh
Исправил что успел,

Не смотри на src/Homes/Filters/Dates/date-picker.js (пробывал через date-picker - не вышло)

Работаю над версиями календаря планшета и мобилы

2018-01-13 09:05 UTC, evgenyrodionov commented
Нахуя игнорить мои замечания?

2018-01-13 09:05 UTC, evgenyrodionov commented
Календарь блевотнейше работает — сам проверь

2018-01-13 09:06 UTC, evgenyrodionov commented
Во-первых, двойной бордер откуда-то взялся, во-вторых, в макете не такой формат дат
![image](https://user-images.githubusercontent.com/775692/34904601-1e704f7c-f85a-11e7-96a4-04771ccf700f.png)

2018-01-13 09:09 UTC, imevro requested changes

2018-01-13 09:09 UTC, evgenyrodionov commented on src/App.js
> +import "./Homes/Filters/Dates/react_dates_overrides.css";
ну и нахуя в АППЕ ходить ТУДА?

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Cards/Paginator.js
> +  font-family: "CircularA ir", Helvetica Neue, Helvetica, Arial, sans-serif;
значение знаешь?

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +import "react-dates/lib/css/_datepicker.css";
то есть у тебя стили реакт-дейтс идут позже твоих (которых в апп.джс импортятся). как тогда твои должны работать?

вынеси в апп джс

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +    css`
зачем тебе хелпер `css`?

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +    this.onDatesChange = this.onDatesChange.bind(this);
читай частые ошибки

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  };
читай чужие пры

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  FilterStatus = (startDateString, endDateString) => {
это компонент? почему паскалькейс? это раз

вынеси из метода класса, я писал в частых ошибках. это два

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  Reset = () => {
это компонент?

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +      <React.Fragment>
ну и зачем тут реакт фрагмент?

2018-01-13 09:09 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +import Dates from "./Dates/index";
зачем индекс?

2018-01-13 20:41 UTC, dskiba commented
deploy: https://build-trxpwvwfok.now.sh/

Честно скажу сломал селекторы в календаре, не смог выявить баг и не вышло, тема лайфциклов дается очень сложно для меня, если на пропсы всю верстку перевести получилось, то тут сложно. Чужое брать не стал. Делал по examples  из react-dates. 
При разработке других фильтров будет разработан единый компонент дропдауна.

2018-01-16 03:02 UTC, dskiba commented
- Исправил замечения. 
- Добавил Dropdown для пследующих фильтров,
- Date-picker сперва смотрит какая ширина экрана, а затем рендерит нужный календарь - верно ли так поступать? До этого  отлавливал в пропсах match width и ставил нужное валуе, сейчас кода получилось больше, но читаемость  и mobile first лучше на мой взгляд.

deploy: https://build-bbfpugrnit.now.sh/

2018-01-20 00:57 UTC, dskiba commented
deploy: https://build-xqtrfkobac.now.sh/

2018-01-21 08:06 UTC, imevro requested changes

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    this.setState({ openedFilter: null, ...values });
нет, спред оператором запрещено пользоваться для чего-либо кроме копирования, потому что явное лучше неявного

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Header/index.jsx
> +  & > .container {
нет

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +import "./react_dates_overrides.css";
почему бы не `ReactDates.css`?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +const Sm = props => <Responsive {...props} maxWidth={575} />;
мб вынести в другую директорию, более общую?

и как оно вообще должно работать, если ты с чилдреном не работаешь?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  return getStartDate(startDate) + " - " + getEndDate(endDate);
используй es template strings

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +    isTouchDevice: true
а это зачем вообще в стейте?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  state = this.initialValues;
нахуя?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +          : props.name}
ебать ты тут наворотил, сам не путаешься? вынеси в функцию и всё

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +                <ConfirmButton onClick={props.onClick}>Cancel</ConfirmButton>
если есть isReset, то показать Cancel, иначе Reset? это как?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +                <ConfirmButton onClick={props.onReset}>Reset</ConfirmButton>
ConfirmButton RESET? это как?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +    & > .container {
НЕТ

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +  toggleFilter = key => {
ты и так в фильтре, ну зачем этот постфикс фильтр?

2018-01-21 08:06 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +          : { openedFilter: key }
почему эту проверку нельзя перенести на поле?

`{ openedFilter: prevState.openedFilter === key ? x : y }`

2018-01-22 00:43 UTC, dskiba commented on src/Homes/Filters/Dates/index.js
> +  state = this.initialValues;
Обозначил для себя входящие данные, в читаемости мне потом легче сравнивать текущие состояние с входным.
Если это непривильно, направь как лучше?

2018-01-22 01:35 UTC, dskiba commented on src/Homes/Filters/index.js
> +          : { openedFilter: key }
toggle = key => {
    this.setState(prevState => {
      openedFilter: prevState.openedFilter === key ? null : key;
    });
  };

Ставил так, и перестало работать, не понимаю в чем  причина

2018-01-22 02:07 UTC, dskiba commented on src/Homes/Filters/Dropdown.js
> +                <ConfirmButton onClick={props.onReset}>Reset</ConfirmButton>
Стиль кнопки одинаковый как у Apply так и Reset
кнопка подтверждения СБРОС 
кнопка подтверждения ПРИМИНЕНИЯ

Button = styled.button
повтор же нейминга?
а дублировать компонент тоже незачем.

2018-01-22 14:35 UTC, imevro requested changes

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +  state = this.initialValues;
а зачем тебе сравнивать вообще?

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +              {props.isCancelOrReset ? (
стало ещё хуже — если кэнсел или резет, показать кнопку конфирма

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/Dates/index.js
> +//     : props.name;
мусор надо выносить

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/Dropdown.js
> +                <ConfirmButton onClick={props.onReset}>Reset</ConfirmButton>
Явное лучше неявного, вот зачем нужно чётко прописать. Ты путаешь людей

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +import { Container } from "../../UI/index";
зачем индекс-то?

2018-01-22 14:35 UTC, evgenyrodionov commented on src/Homes/Filters/index.js
> +          : { openedFilter: key }
так демку на кодсандбокс и в чат

2018-01-22 23:10 UTC, imevro approved these changes

2018-01-22 23:11 UTC, merged