Feat/homes filters
dskiba/airbnb-demo-frontend pull request #4
Opened 2018-01-24 01:28 UTC by dskiba

deploy: https://build-avwvzixfjn.now.sh

2018-01-24 10:08 UTC, evgenyrodionov commented
Дизайн окна чё-то по пизде пошёл, но зато правильно работает
![image](https://user-images.githubusercontent.com/775692/35326438-b84116d0-0107-11e8-80ac-1341cb173520.png)

2018-01-24 10:22 UTC, imevro requested changes

2018-01-24 10:22 UTC, evgenyrodionov commented on .eslintrc.json
> +      "error",
да просто выруби это правило и всё

2018-01-24 10:22 UTC, evgenyrodionov commented on .eslintrc.json
> +        "specialLink": ["to", "hrefLeft", "hrefRight"],
но за то что разобрался с настройками правил — респект

2018-01-24 10:22 UTC, evgenyrodionov commented on src/Homes/Cards/Card.js
> +import Stars from '../../UI/Stars/index';
а зачем index указываешь?

2018-01-24 10:22 UTC, evgenyrodionov commented on src/Homes/Cards/Card.js
> +import Stars from '../../UI/Stars/index';
я же писал аж во втором уроке про то, что вебпак сам ищет `index.js` и поэтому можно не указывать

2018-01-24 10:22 UTC, evgenyrodionov commented on src/Homes/Filters/Guests/index.js
> +  //     openedFilter: prevState.openedFilter === key ? null : key,
мусор выкинь

2018-01-24 10:22 UTC, evgenyrodionov commented on src/Homes/Filters/Guests/index.js
> +  onReset = () => this.setState({ guests: { adults: 1, children: 0, infants: 0 } });
а почему тогда уж не this.initialValues?

2018-01-24 10:22 UTC, evgenyrodionov commented on src/Homes/GoogleMap.js
> +            key: process.env.REACT_APP_SECRET_CODE,
только щас заметил, что REACT_APP_SECRET_CODE плохое название — неочевидно, что это ключ от карт

2018-01-26 13:17 UTC, evgenyrodionov commented
А деплой где?

2018-01-26 13:18 UTC, imevro reviewed
по коду ок, но нужен деплой

2018-01-27 05:52 UTC, dskiba commented
deploy: https://build-hqexahwzkd.now.sh

Фильтр "More Filters": не реализован подсчет всех фильтров с выдачей в тайтл

2018-01-27 12:56 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/35472143-907b0474-037a-11e8-9b09-c1d8be5262f6.png)

2018-01-27 12:57 UTC, imevro requested changes

2018-01-27 12:57 UTC, evgenyrodionov commented on src/Homes/Filters/MoreFilters/index.js
> +  onCountChange = (key, room) => {
а почему нельзя использовать тот же onChange?

2018-01-27 17:28 UTC, dskiba commented on src/Homes/Filters/MoreFilters/index.js
> +  onCountChange = (key, room) => {
структура чуть разная, onChange для чекбоксов
onCountChange - очень схоже, но здесь + 1 счетчик

2018-01-27 20:53 UTC, dskiba commented
https://build-mxulveaeef.now.sh

2018-01-28 18:44 UTC, imevro approved these changes

2018-01-28 18:45 UTC, merged