Add API for Main Page and Homes Page
dskiba/airbnb-demo-frontend pull request #5
Opened 2018-02-01 02:43 UTC by dskiba

deploy: [airbnb-demo-frontend](https://build-qmxkwhbueq.now.sh/)

- Add lists of homes (18 for Main page, 6 for Homes page)

2018-02-01 16:54 UTC, imevro requested changes
не пизди у Никиты

2018-02-01 16:54 UTC, evgenyrodionov commented on src/Homes/Cards/api.js
> +      return 'Private room';
читай второй урок первой этапа

2018-02-01 16:54 UTC, evgenyrodionov commented on src/Homes/Cards/api.js
> +    .then(res => res.items)
зачем?

2018-02-01 16:54 UTC, evgenyrodionov commented on src/Main/Homes/index.js
> +import { HomesData } from '../../Homes/Cards/api';
это компонент? почему он называется в ПаскальКейсе?

2018-02-02 02:04 UTC, dskiba commented
[Deploy](https://build-ofysbuhseh.now.sh/)

- Fix Requested Changes
- Add Loader (need to improve)
- Add Markers at GoogleMap

2018-02-03 10:26 UTC, imevro requested changes

2018-02-03 10:26 UTC, evgenyrodionov commented on src/Homes/GoogleMap.js
> +    const homes = await homesData(0, 6);
а зачем ты в карте запрашиваешь ещё раз? где синхронизация?

кстати, забыл в прошлый раз сказать что плохое название функции, должно быть что-то типа getHomes

2018-02-03 17:52 UTC, dskiba commented
Deploy: [air-bnb-demo](https://build-zspheiifip.now.sh/)

- eslint errors 
- fix sync data from API between components
- fix imgs

2018-02-04 15:35 UTC, imevro requested changes
исправишь — смерджишь через сквош

2018-02-04 15:35 UTC, evgenyrodionov commented on src/Homes/Cards/api.js
> +export default function getHomes(offset, limit) {
а что вообще этот файл делает в Cards вместо Homes?

2018-02-05 20:59 UTC, merged